server:
  port: 8513

spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.180.4:8848
  config:
    import: application-alipay.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.70.180.4:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: qwert@520
  data:
    redis:
      host: 124.70.180.4
      port: 6379
      password: redis
      database: 2
mybatis:
  #  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.zenith.spzx.order: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
