server:
  port: 8512

spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.180.4:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.70.180.4:3306/db_spzx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: qwert@520
  data:
    redis:
      host: 124.70.180.4
      port: 6379
      password: redis
      database: 2

mybatis:
  #  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.zenith.spzx.user: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
sms:
  AppCode: 811aa70789f94c37a67009fa41857133
